function Configuration(){
	this.BASE_URL = "https://domain_name/";
	this.LOGIN_URL = "login/authenticate";
	this.ENABLE_CONSOLE_LOGS = true;

	this.SUCCESS_STATUS_TEXT = "SUCCESS";
	this.FAILURE_STATUS_TEXT = "FAILURE";
	this.INVALID_TOKEN_TEXT = "INVALID_TOKEN";
	this.TOKEN_ABSENT_TEXT = "TOKEN_ABSENT";
	this.TOKEN_EXPIRED_TEXT = "TOKEN_EXPIRED";
	this.UPDATE_LOGIN_STATUS_URL = "user/updateLoginFlag";
	this.EXECUTE_SCRIPT_URL = "appBuild/add";
	this.GET_EXECUTION_HISTORY_URL = "appBuild/listAll";
	this.ADD_CONFIGURATION_URL = "appInfo/add";
	this.LIST_CONFIGURATIONS_URL = "appInfo/listAll";
	this.UPDATE_CONFIGURATION_URL = "appInfo/update";
	this.DASHBOARD_LIST_URL = "dashboard/getData";

	this.HTTP_STATUS_CODE = 200;
	this.TOKEN_EXPIRED_CODE = 405;
	this.INVALID_TOKEN_CODE = 406;
	this.TOKEN_ABSENT_CODE = 407;
	this.LOGIN_SUCCESS_CODE = 1000;
	this.UPDATE_LOGIN_STATUS_SUCCESS_CODE = 50000;
	this.EXECUTE_SCRIPT_SUCCESS_CODE = 2000;
	this.EXECUTE_SCRIPT_FAILURE_CODE = 2002;
	this.EXECUTE_SCRIPT_RUNNING_A_BUILD_FAILURE_CODE = 2003;
	this.GET_EXECUTION_HISTORY_SUCCESS_CODE = 3000;
	this.ADD_CONFIGURATION_SUCCESS_CODE = 4000;
	this.LIST_CONFIGURATIONS_SUCCESS_CODE = 5000;
	this.UPDATE_CONFIGURATION_SUCCESS_CODE = 6000;
	this.DASHBOARD_LIST_SUCCESS_CODE = 6000;
}
